In [1]:
import numpy as np

In [8]:
p = np.array([[7.2],
              [-2.1],
              [1]])

T = np.array([[1,0,3.3],
              [0,1,5.5],
              [0,0,1]])

R = np.array([[np.cos(.5),-np.sin(.5),0],
              [np.sin(.5),np.cos(.5),0],
              [0,0,1]])

In [9]:
result = np.matmul(T,p)
print(result)

[[7.32538808]
 [1.6089405 ]
 [1.        ]]


In [10]:
result = np.matmul(R,p)
print(result)

[[7.32538808]
 [1.6089405 ]
 [1.        ]]


In [15]:
M1 = np.matmul(T,R) #Rotate then translate
M2 = np.matmul(R,T) #Translate then Rotate

print(M2)

[[ 0.87758256 -0.47942554  0.25918199]
 [ 0.47942554  0.87758256  6.40880837]
 [ 0.          0.          1.        ]]


In [12]:
result = np.matmul(M1,p)
print(result)

[[10.62538808]
 [ 7.1089405 ]
 [ 1.        ]]


In [13]:
result = np.matmul(M2,p)
print(result)

[[7.58457007]
 [8.01774887]
 [1.        ]]


In [16]:
#new_center = (-1.7,4.0)

Tc = np.array([[1,0,-1.7],
              [0,1,4.0],
              [0,0,1]])

Tc_in = np.array([[1,0,1.7],
              [0,1,-4.0],
              [0,0,1]])

# Rotation about a new center
M3 = np.matmul(Tc,np.matmul(R,Tc_in))

In [17]:
result = np.matmul(M3,p)
print(result)

[[9.03498059]
 [2.91363367]
 [1.        ]]
