In [1]:
import numpy as np

In [3]:
p = np.array([[2.1], [3.7]])

print(p)

[[2.1]
 [3.7]]


In [6]:
ang = 1.2 #radians

R = np.array([[np.cos(ang),-np.sin(ang)],
              [np.sin(ang),np.cos(ang)]])

print(R)

[[ 0.36235775 -0.93203909]
 [ 0.93203909  0.36235775]]


In [8]:
p2 = np.matmul(R, p)

print(p2)

[[-2.68759333]
 [ 3.29800577]]
